export const mutations = {
    'INIT_BOOKS':'INIT_BOOKS',
    'ADD_BOOK':'ADD_BOOK',
    'SAVE_BOOKS':'SAVE_BOOKS',
    'UPDATE_BOOK':'UPDATE_BOOK',
    'DELETE_BOOK':'DELETE_BOOK',
    'TOGGLE_STATUS_BOOK':'TOGGLE_STATUS_BOOK',
    'REMOVE_ALL_BOOKS':'REMOVE_ALL_BOOKS',
    'SELECT_BOOK':'SELECT_BOOK',
}

export const actions = {
    'INIT_BOOKS':'INIT_BOOKS',
    'ADD_BOOK':'ADD_BOOK',
    'UPDATE_BOOK':'UPDATE_BOOK',
    'DELETE_BOOK':'DELETE_BOOK',
    'TOGGLE_STATUS_BOOK':'TOGGLE_STATUS_BOOK',
    'SAVE_BOOKS':'SAVE_BOOKS',
    'REMOVE_ALL_BOOKS':'REMOVE_ALL_BOOKS',
    'SELECT_BOOK':'SELECT_BOOK',
}